
ALTER TABLE public.user_cards 
  ADD COLUMN IF NOT EXISTS stat_rap integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stat_tir integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stat_pas integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stat_dri integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stat_phy integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS position text NOT NULL DEFAULT 'BU',
  ADD COLUMN IF NOT EXISTS overall integer NOT NULL DEFAULT 0;
